name: todo_new
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  another_flushbar: ^1.12.29
  auto_route: ^5.0.4
  cloud_firestore: ^4.3.1
  dartz: ^0.10.1
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flex_color_scheme: ^6.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  get_it: ^7.2.0
  google_sign_in: ^5.4.3
  injectable: ^2.1.0
  json_annotation: ^4.8.0
  uuid: ^3.0.7

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.3.2
  injectable_generator: ^2.1.3
  json_serializable: ^6.6.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
